import type { Language } from '../../domain/user-config.js';

const copy = {
  tr: {
    homeTitle: 'İndirim radarın',
    homeDescription: 'Steam wishlist indirimlerini, bildirimlerini ve mağaza ayarlarını tek yerden yönet.',
    homeWishlist: 'Wishlist’i Aç',
    homeCheck: 'Şimdi Kontrol Et',
    homeSettings: 'Bildirim Ayarları',
    homeRegionLanguage: 'Bölge ve Dil',
    homeTest: 'Test DM’i Gönder',
    homeRefresh: 'Yenile',
    account: 'Hesap',
    tracking: 'İzleme',
    notifications: 'Bildirim',
    lastCheck: 'Son Kontrol',
    configured: 'Kurulu',
    notConfigured: 'Kurulmamış',
    active: 'Açık',
    paused: 'Kapalı',
    dmReady: 'DM teslimatı hazır',
    dmBlocked: 'Discord DM’leri engelliyor',
    never: 'Henüz yok',
    wishlistTitle: 'Steam Wishlist’in',
    wishlistSummary: (shown: number, total: number, sale: number) =>
      `**${shown}/${total} oyun gösteriliyor** · **${sale} indirimde**`,
    wishlistAll: 'Tümü',
    wishlistSale: 'İndirimdekiler',
    wishlistDiscount: 'En yüksek indirim',
    wishlistRecent: 'Son eklenen',
    wishlistViewPlaceholder: 'Wishlist görünümünü seç',
    wishlistRulePlaceholder: 'Bir oyunun bildirim eşiğini değiştir',
    wishlistEmptyFiltered: 'Bu görünümde gösterilecek oyun bulunamadı.',
    wishlistPriceUnknown: 'Fiyat bilgisi alınamadı',
    wishlistFree: 'Ücretsiz',
    wishlistThreshold: (percent: number, override: boolean) =>
      `Bildirim eşiği: **%${percent}**${override ? ' · Oyuna özel' : ' · Genel ayar'}`,
    previous: 'Önceki',
    next: 'Sonraki',
    close: 'Kapat',
    page: (current: number, total: number) => `${current} / ${total}`,
    checkingTitle: 'Wishlist kontrol ediliyor',
    checkingDescription: 'Steam fiyatları güvenli biçimde karşılaştırılıyor. Bu işlem kısa sürebilir.',
    checkSuccessTitle: 'Kontrol tamamlandı',
    checkUnavailableTitle: 'Steam şu anda yanıt vermiyor',
    checkFailedTitle: 'Kontrol tamamlanamadı',
    checkAlreadyTitle: 'Kontrol zaten çalışıyor',
    checkCooldownTitle: 'Biraz beklemelisin',
    openStatus: 'Durumu Aç',
    openWishlist: 'Wishlist’i Aç',
    regionTitle: 'Steam mağaza bölgesi',
    regionDescription: 'Fiyatların gösterileceği Steam Store ülkesini seç.',
    regionRangePlaceholder: 'Alfabetik ülke aralığını seç',
    regionCountryPlaceholder: 'Ülkeni seç',
    regionOther: 'Listede yok · tüm ülkeler ve arama',
    back: 'Geri',
    deleteTitle: 'Dealio verilerini kalıcı olarak sil',
    deleteDescription: 'Steam bağlantın, fiyat geçmişin, bildirim kuralların ve teslimat kayıtların silinir. Bu işlem geri alınamaz.',
    deleteOpenConfirm: 'Silme Onayını Aç',
    deleteCancel: 'Vazgeç',
    deleteModalTitle: 'Kalıcı silme onayı',
    deleteConsentLabel: 'Devam etmek için onayla',
    deleteConsentOption: 'Tüm Dealio verilerimin kalıcı silinmesini onaylıyorum',
    deleteSuccessTitle: 'Verilerin silindi',
    deleteNoDataTitle: 'Silinecek veri bulunamadı',
    setupAgain: 'Yeni Kurulum Başlat',
    testSentTitle: 'Test DM’i gönderildi',
    testFailedTitle: 'Test DM’i gönderilemedi',
    testCooldownTitle: 'Test bildirimi beklemede',
    testSentDescription: 'DM kutunu kontrol edebilirsin. Gelen kart gerçek bildirim tasarımının bir örneğidir.',
    sessionExpired: 'Bu panelin süresi doldu. Güncel panel için komutu yeniden çalıştır.',
  },
  en: {
    homeTitle: 'Your sale radar',
    homeDescription: 'Manage Steam wishlist sales, notifications, and Store settings in one place.',
    homeWishlist: 'Open Wishlist',
    homeCheck: 'Check Now',
    homeSettings: 'Notification Settings',
    homeRegionLanguage: 'Region & Language',
    homeTest: 'Send Test DM',
    homeRefresh: 'Refresh',
    account: 'Account',
    tracking: 'Tracking',
    notifications: 'Notifications',
    lastCheck: 'Last Check',
    configured: 'Configured',
    notConfigured: 'Not configured',
    active: 'Active',
    paused: 'Paused',
    dmReady: 'DM delivery ready',
    dmBlocked: 'Discord is blocking DMs',
    never: 'Not available yet',
    wishlistTitle: 'Your Steam Wishlist',
    wishlistSummary: (shown: number, total: number, sale: number) =>
      `**Showing ${shown}/${total} games** · **${sale} on sale**`,
    wishlistAll: 'All games',
    wishlistSale: 'On sale',
    wishlistDiscount: 'Highest discount',
    wishlistRecent: 'Recently added',
    wishlistViewPlaceholder: 'Choose a wishlist view',
    wishlistRulePlaceholder: 'Change a game notification threshold',
    wishlistEmptyFiltered: 'There are no games to show in this view.',
    wishlistPriceUnknown: 'Price unavailable',
    wishlistFree: 'Free',
    wishlistThreshold: (percent: number, override: boolean) =>
      `Alert threshold: **${percent}%**${override ? ' · Game-specific' : ' · Global'}`,
    previous: 'Previous',
    next: 'Next',
    close: 'Close',
    page: (current: number, total: number) => `${current} / ${total}`,
    checkingTitle: 'Checking your wishlist',
    checkingDescription: 'Steam prices are being compared safely. This may take a moment.',
    checkSuccessTitle: 'Check complete',
    checkUnavailableTitle: 'Steam is currently unavailable',
    checkFailedTitle: 'Check could not be completed',
    checkAlreadyTitle: 'A check is already running',
    checkCooldownTitle: 'Please wait a little',
    openStatus: 'Open Status',
    openWishlist: 'Open Wishlist',
    regionTitle: 'Steam Store region',
    regionDescription: 'Choose the Steam Store country used for prices.',
    regionRangePlaceholder: 'Choose an alphabetical country range',
    regionCountryPlaceholder: 'Choose your country',
    regionOther: 'Not listed · all countries and search',
    back: 'Back',
    deleteTitle: 'Permanently delete Dealio data',
    deleteDescription: 'Your Steam connection, price history, notification rules, and delivery records will be deleted. This cannot be undone.',
    deleteOpenConfirm: 'Open Delete Confirmation',
    deleteCancel: 'Cancel',
    deleteModalTitle: 'Permanent deletion confirmation',
    deleteConsentLabel: 'Confirm to continue',
    deleteConsentOption: 'I confirm permanent deletion of all my Dealio data',
    deleteSuccessTitle: 'Your data was deleted',
    deleteNoDataTitle: 'No data was found to delete',
    setupAgain: 'Start New Setup',
    testSentTitle: 'Test DM sent',
    testFailedTitle: 'Test DM could not be sent',
    testCooldownTitle: 'Test notification is on cooldown',
    testSentDescription: 'Check your DMs. The card you received is an example of the real notification design.',
    sessionExpired: 'This panel has expired. Run the command again for a fresh panel.',
  },
} as const;

export function uiCopy(language: Language): typeof copy.tr | typeof copy.en {
  return copy[language];
}
